# https://taskfile.dev
# To enable experimental features
# export TASK_X_FEATURE=1
# export TASK_X_REMOTE_TASKFILES=1
# https://taskfile.dev/docs/experiments/remote-taskfiles

version: "3"
dotenv: [".env", ".env.example", "{{.HOME}}/.env"]

vars:
  TASK_REMOTE: "github.com/lwmacct/251207-task-remote.git//.task"

includes:
  env:
    taskfile: https://{{.TASK_REMOTE}}/env.yml?ref=main
    optional: true
    flatten: true

  git:
    taskfile: https://{{.TASK_REMOTE}}/git.yml?ref=main
    optional: true

  go:
    taskfile: https://{{.TASK_REMOTE}}/go.yml?ref=main
    optional: true

  cmd:
    taskfile: .task/cmd.yml
    optional: true
